[program:{{=project}}]
command = {{=server}} --bind {{=host}}:{{=port}} --workers {{=workers}} --log-level {{=log_level}} {{=project}}.uliweb_asgi:application
directory={{=project_dir}}
stopsignal=QUIT
autostart=true
autorestart=true
stdout_logfile=/tmp/{{=project}}.log
redirect_stderr=true
exitcodes=0,1,2
{{if defined('python_path'):}}
environment=PYTHONPATH="{{=python_path}}"
{{pass}}
